# Generated by Django 3.2.3 on 2021-05-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pomodoros_completed',
            field=models.IntegerField(default=0),
        ),
    ]
