# Generated by Django 3.2.3 on 2021-06-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0005_remove_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passcode',
        ),
    ]
